site_name: tinyBIG
site_url: https://www.tinybig.org/
repo_url: https://github.com/jwzhanggy/tinyBIG

theme:
  name: "material"
  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  font:
    text: Roboto
  palette:
    primary: "deep purple"
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.expand
    - navigation.path
    - navigation.top
    - toc.follow
    - header.autohide
    - navigation.footer

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jwzhanggy/tinyBIG

markdown_extensions:
  - tables

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            heading_level: 3
  - macros:
      module_name: docs/env

nav:
  - index.md
  - Get Started:
    - Overview: guides/overview.md
    - Installation: guides/install.md
  - Docs:
    - Overview: documentations/index.md
    - documentations/tinybig.md
    - documentations/expansion.md
    - documentations/reconciliation.md
    - documentations/remainder.md
    - documentations/module.md
    - documentations/model.md
    - documentations/config.md
    - documentations/learner.md
    - documentations/data.md
    - documentations/output.md
    - documentations/metric.md
    - documentations/util.md
  - Tutorials: tutorials/index.md
  - Examples: examples/index.md
  - References: references/index.md